const issnetonline100 = {
    consultarLoteRpsEnvio: "ConsultarLoteRpsEnvio",
    enviarLoteRpsEnvio: "EnviarLoteRpsEnvio",
    cancelarNfseEnvio: "CancelarNfseEnvio",
    consultarNfseRpsEnvio: "ConsultarNfseRpsEnvio",
    consultarNfseEnvio: "ConsultarNfseEnvio",
    consultarSituacaoLoteRpsEnvio: "ConsultarSituacaoLoteRpsEnvio",

    identificacaoRps: "IdentificacaoRps",
    tcNumero: "tc:Numero",
    tcSerie: "tc:Serie",
    tcTipo: "tc:Tipo",
    prestador: "Prestador",
    tcCpfCnpj: "tc:CpfCnpj",
    tcCnpj: "tc:Cnpj",
    tcInscricaoMunicipal: "tc:InscricaoMunicipal",
    cpfCnpj: "CpfCnpj",
    cnpj: "Cnpj",


    loteRps: "LoteRps",
    numeroLote: "NumeroLote",
    quantidadeRps: "QuantidadeRps",
    listaRps: "ListaRps",
    rps: "Rps",
    infRps: "InfRps",
    dataEmissao: "DataEmissao",
    naturezaOperacao: "NaturezaOperacao",
    regimeEspecialTributacao: "RegimeEspecialTributacao",
    optanteSimplesNacional: "OptanteSimplesNacional",
    incentivadorCultural: "IncentivadorCultural",
    status: "Status",
    rpsSubstituido: "RpsSubstituido",
    numero: "Numero",
    serie: "Serie",
    tipo: "Tipo",
    servico: "Servico",
    valores: "Valores",
    valorServicos: "ValorServicos",
    valorDeducoes: "ValorDeducoes",
    valorPis: "ValorPis",
    valorCofins: "ValorCofins",
    valorInss: "ValorInss",
    valorIr: "ValorIr",
    valorCsll: "ValorCsll",
    issRetido: "IssRetido",
    valorIss: "ValorIss",
    valorIssRetido: "ValorIssRetido",
    outrasRetencoes: "OutrasRetencoes",
    baseCalculo: "BaseCalculo",
    aliquota: "Aliquota",
    valorLiquidoNfse: "ValorLiquidoNfse",
    descontoIncondicionado: "DescontoIncondicionado",
    descontoCondicionado: "DescontoCondicionado",
    itemListaServico: "ItemListaServico",
    codigoCnae: "CodigoCnae",
    codigoTributacaoMunicipio: "CodigoTributacaoMunicipio",
    discriminacao: "Discriminacao",
    codigoMunicipio: "CodigoMunicipio",
    inscricaoMunicipal: "InscricaoMunicipal",
    tomador: "Tomador",
    identificacaoTomador: "IdentificacaoTomador",
    razaoSocial: "RazaoSocial",
    endereco: "Endereco",
    endereco: "Endereco",
    numero: "Numero",
    complemento: "Complemento",
    bairro: "Bairro",
    codigoMunicipio: "CodigoMunicipio",
    uf: "Uf",
    cep: "Cep",
    contato: "Contato",
    telefone: "Telefone",
    email: "Email",
    intermediarioServico: "IntermediarioServico",
    razaoSocial: "RazaoSocial",
    inscricaoMunicipal: "InscricaoMunicipal",
    contrucaoCivil: "ContrucaoCivil",
    codigoObra: "CodigoObra",
    art: "Art",
    protocolo: "Protocolo",
    infPedidoCancelamento: "InfPedidoCancelamento",
    pedido: "Pedido",
    identificacaoNfse: "IdentificacaoNfse",
    codigoCancelamento: "CodigoCancelamento"
};

module.exports = {
    issnetonline100
}